TOPLEVEL_DIR := $(shell git rev-parse --show-toplevel)

TOPLEVEL     = ifu
MODULE       = test_ifu
VERILOG_SOURCES = $(TOPLEVEL_DIR)/rtl/core/ifu/ifu.sv

include $(TOPLEVEL_DIR)/tb/common/Makefile.include
