TOPLEVEL_DIR := $(shell git rev-parse --show-toplevel)

TOPLEVEL     = ieu
MODULE       = test_ieu
VERILOG_SOURCES = $(TOPLEVEL_DIR)/rtl/core/ieu/ieu.sv

include $(TOPLEVEL_DIR)/tb/common/Makefile.include
