TOPLEVEL_DIR := $(abspath ../../..)

TOPLEVEL = obi_decoder
MODULE   = test_obi_decoder
VERILOG_SOURCES = $(TOPLEVEL_DIR)/config/hipv_soc_pkg.sv \
                  $(TOPLEVEL_DIR)/rtl/interconnect/obi_decoder.sv

include $(TOPLEVEL_DIR)/tb/common/Makefile.include
