TOPLEVEL_DIR := $(shell git rev-parse --show-toplevel)

TOPLEVEL     = hipv_core
MODULE       = test_hipv_core
VERILOG_SOURCES = $(TOPLEVEL_DIR)/rtl/core/hipv_core.sv

include $(TOPLEVEL_DIR)/tb/common/Makefile.include
