TOPLEVEL_DIR := $(abspath ../../..)

TOPLEVEL     = regfile
MODULE       = test_regfile
VERILOG_SOURCES = $(TOPLEVEL_DIR)/rtl/core/regfile/regfile.sv

include $(TOPLEVEL_DIR)/tb/common/Makefile.include
