TOPLEVEL_DIR := $(abspath ../../..)

TOPLEVEL = wbu
MODULE   = test_wbu
VERILOG_SOURCES = $(TOPLEVEL_DIR)/config/hipv_pkg.sv \
                  $(TOPLEVEL_DIR)/rtl/generic/flopenr.sv \
                  $(TOPLEVEL_DIR)/rtl/generic/mux3.sv \
                  $(TOPLEVEL_DIR)/rtl/core/wbu/wbu.sv

include $(TOPLEVEL_DIR)/tb/common/Makefile.include
