TOPLEVEL_DIR := $(shell git rev-parse --show-toplevel)

TOPLEVEL     = wbu
MODULE       = test_wbu
VERILOG_SOURCES = $(TOPLEVEL_DIR)/rtl/core/wbu/wbu.sv

include $(TOPLEVEL_DIR)/tb/common/Makefile.include
