TOPLEVEL_DIR := $(shell git rev-parse --show-toplevel)

TOPLEVEL     = idu
MODULE       = test_idu
VERILOG_SOURCES = $(TOPLEVEL_DIR)/rtl/core/idu/idu.sv

include $(TOPLEVEL_DIR)/tb/common/Makefile.include
