TOPLEVEL_DIR := $(shell git rev-parse --show-toplevel)

TOPLEVEL     = lsu
MODULE       = test_lsu
VERILOG_SOURCES = $(TOPLEVEL_DIR)/rtl/core/lsu/lsu.sv

include $(TOPLEVEL_DIR)/tb/common/Makefile.include
