TOPLEVEL_DIR := $(shell git rev-parse --show-toplevel)

TOPLEVEL     = hazard
MODULE       = test_hazard
VERILOG_SOURCES = $(TOPLEVEL_DIR)/rtl/core/hazard/hazard.sv

include $(TOPLEVEL_DIR)/tb/common/Makefile.include
