TOPLEVEL_DIR := $(abspath ../../..)

TOPLEVEL = hazard
MODULE   = test_hazard
VERILOG_SOURCES = $(TOPLEVEL_DIR)/config/hipv_pkg.sv \
                  $(TOPLEVEL_DIR)/rtl/core/hazard/hazard.sv

include $(TOPLEVEL_DIR)/tb/common/Makefile.include
